apiVersion: v2
name: files-server
description: A Helm chart for files-server
type: application
version: 2.2.2
appVersion: 2.2.2
dependencies:
  - name: nginx
    version: 1.3.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm
