apiVersion: v2
name: files-server
description: A Helm chart for files-server
type: application
version: 2.1.1
appVersion: 2.1.1
dependencies:
  - name: nginx
    version: 1.3.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
