name: Build and push artifacts

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Login to ACR
        uses: MapColonies/artifactory-login@v1.0.0
        with:
          username: ${{ secrets.ACR_PUSH_USER }}
          password: ${{ secrets.ACR_PUSH_TOKEN }}
          registry: acrarolibotnonprod.azurecr.io

      - name: Build and Push Helm Chart
        uses: MapColonies/build-and-push-helm@v1.0.1
        with:
          domain: raster
          project: ${{ github.repository }}
          tag: ${{ github.ref_name }}
          registry_url: acrarolibotnonprod.azurecr.io

      - name: Update Artifacts File
        uses: MapColonies/update-artifacts-file@v1.1.1
        with:
          domain: raster
          project: ${{ github.repository }}
          tag: ${{ github.ref_name }}
